
ifndef SILENCE
#  SILENCE = @
endif

CPP_PLATFORM = Gcc

COMPONENT_NAME = KOZOS
CPPUTEST_HOME = /usr/local

CPPUTEST_USE_EXTENSIONS = N
CPPUTEST_USE_GCOV = Y

#SRC_DIRS =\
# ../misc

#SRC_FILES = ../src/misc/serial.c

TEST_SRC_DIRS = .

INCLUDE_DIRS =\
  .\
  ../src/misc\
  $(CPPUTEST_HOME)/include\

include MakefileWorker.mk
